apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: tasks-app
  labels:
    app.kubernetes.io/name: locust
    app.kubernetes.io/component: load-test
    app.kubernetes.io/part-of: task-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: locust
  ports:
    - name: web
      port: 8089
      targetPort: web
      protocol: TCP
